import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
function App(){
 const[token,setToken]=useState(localStorage.onboardkit||'');const[clients,setClients]=useState([]);const[mode,setMode]=useState('register');const[error,setError]=useState('');
 async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}});const d=r.status===204?null:await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
 const load=()=>token&&api('/clients').then(setClients).catch(e=>setError(e.message));useEffect(load,[token]);
 async function auth(e){e.preventDefault();try{const d=await api('/auth/'+mode,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});localStorage.onboardkit=d.token;setToken(d.token)}catch(x){setError(x.message)}}
 async function add(e){e.preventDefault();try{await api('/clients',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});e.currentTarget.reset();load()}catch(x){setError(x.message)}}
 async function complete(task){try{await api('/tasks/'+task._id,{method:'PATCH',body:JSON.stringify({status:'done',note:'Completed from dashboard'})});load()}catch(x){setError(x.message)}}
 if(!token)return <main className="auth"><section><h1>OnboardKit</h1><p>Turn every new client into a confident launch.</p></section><form onSubmit={auth}><h2>{mode==='register'?'Create workspace':'Welcome back'}</h2>{mode==='register'&&<><input name="workspace" placeholder="Workspace" required/><input name="name" placeholder="Your name" required/></>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" minLength="8" placeholder="Password" required/><button>{mode==='register'?'Start onboarding':'Sign in'}</button><a onClick={()=>setMode(mode==='register'?'login':'register')}>{mode==='register'?'Use an existing account':'Create a workspace'}</a><p className="error">{error}</p></form></main>;
 return <><header><div><h1>OnboardKit</h1><span>Client implementation workspace</span></div><button className="quiet" onClick={()=>{localStorage.removeItem('onboardkit');setToken('')}}>Sign out</button></header><main><div className="layout"><form onSubmit={add}><h2>New client</h2><input name="company" placeholder="Company" required/><input name="contactName" placeholder="Contact name" required/><input name="contactEmail" type="email" placeholder="Contact email" required/><input name="owner" placeholder="Internal owner" required/><label>Target launch</label><input name="targetDate" type="date" required/><button>Create onboarding</button></form><section><h2>Active onboardings</h2><div className="cards">{clients.map(c=><article key={c._id}><div className="row"><span className="pill">{c.status}</span><b>{c.progress}% complete</b></div><h3>{c.company}</h3><p>{c.contactName} · {c.owner} · {new Date(c.targetDate).toLocaleDateString()}</p>{c.tasks.map(t=><div className="task" key={t._id}><span>{t.title}<small>{t.category} / {t.assignee}</small></span><button disabled={t.status==='done'} onClick={()=>complete(t)}>{t.status==='done'?'Done':'Complete'}</button></div>)}</article>)}</div></section></div><p className="error">{error}</p></main></>;
}createRoot(document.getElementById('root')).render(<App/>);

