import {Router} from 'express';import bcrypt from 'bcryptjs';import mongoose from 'mongoose';
import {Check,Release,User} from './models.js';import {signToken,requireAuth} from './auth.js';import {checkSchema,loginSchema,readiness,registerSchema,releaseSchema,resultSchema} from './validation.js';
export const router=Router();
router.post('/auth/register',async(req,res,next)=>{try{const d=registerSchema.parse(req.body);if(await User.exists({email:d.email.toLowerCase()}))return res.status(409).json({error:'Email already registered'});const user=await User.create({tenantId:new mongoose.Types.ObjectId(),name:d.name,email:d.email,passwordHash:await bcrypt.hash(d.password,12)});res.status(201).json({token:signToken(user),workspace:d.workspace})}catch(e){next(e)}});
router.post('/auth/login',async(req,res,next)=>{try{const d=loginSchema.parse(req.body);const user=await User.findOne({email:d.email.toLowerCase()});if(!user||!await bcrypt.compare(d.password,user.passwordHash))return res.status(401).json({error:'Invalid credentials'});res.json({token:signToken(user)})}catch(e){next(e)}});
router.use(requireAuth);
router.get('/releases',async(req,res)=>{const releases=await Release.find({tenantId:req.auth.tenantId}).sort({targetDate:1}).lean();const output=await Promise.all(releases.map(async release=>{const checks=await Check.find({tenantId:req.auth.tenantId,releaseId:release._id}).lean();return {...release,checks,readiness:readiness(checks)}}));res.json(output)});
router.post('/releases',async(req,res,next)=>{try{const d=releaseSchema.parse(req.body);res.status(201).json(await Release.create({...d,tenantId:req.auth.tenantId}))}catch(e){next(e)}});
router.post('/releases/:id/checks',async(req,res,next)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(404).json({error:'Release not found'});const release=await Release.findOne({_id:req.params.id,tenantId:req.auth.tenantId});if(!release)return res.status(404).json({error:'Release not found'});const d=checkSchema.parse(req.body);res.status(201).json(await Check.create({...d,releaseId:release._id,tenantId:req.auth.tenantId}))}catch(e){next(e)}});
router.patch('/checks/:id',async(req,res,next)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(404).json({error:'Check not found'});const d=resultSchema.parse(req.body);const check=await Check.findOneAndUpdate({_id:req.params.id,tenantId:req.auth.tenantId},d,{new:true});if(!check)return res.status(404).json({error:'Check not found'});res.json(check)}catch(e){next(e)}});
router.patch('/releases/:id/ready',async(req,res)=>{const release=await Release.findOne({_id:req.params.id,tenantId:req.auth.tenantId});if(!release)return res.status(404).json({error:'Release not found'});const checks=await Check.find({tenantId:req.auth.tenantId,releaseId:release._id}).lean();const state=readiness(checks);if(!state.ready)return res.status(409).json({error:'Every check must pass before release approval',readiness:state});release.status='ready';await release.save();res.json(release)});

