import {Router} from 'express';import bcrypt from 'bcryptjs';import {Workspace,User,Desk,Booking} from './models.js';import {requireAuth,sign} from './auth.js';import {validEmail,validateDesk,validateBooking} from './validation.js';export const router=Router();
router.post('/auth/register',async(req,res,next)=>{const{workspace,name,email,password}=req.body;if(!workspace?.trim()||!name?.trim()||!validEmail(email)||String(password||'').length<8)return res.status(422).json({error:'Workspace, name, valid email, and password of 8+ characters are required'});try{if(await User.exists({email:email.toLowerCase()}))return res.status(409).json({error:'Email already registered'});const tenant=await Workspace.create({name:workspace});try{const user=await User.create({workspaceId:tenant.id,name,email,passwordHash:await bcrypt.hash(password,12)});res.status(201).json({token:sign(user),user:{id:user.id,name:user.name,workspace:tenant.name}})}catch(error){await Workspace.deleteOne({_id:tenant.id});throw error}}catch(error){if(error.code===11000)return res.status(409).json({error:'Email already registered'});next(error)}});
router.post('/auth/login',async(req,res)=>{const user=await User.findOne({email:String(req.body.email||'').toLowerCase()}).populate('workspaceId');if(!user||!await bcrypt.compare(req.body.password||'',user.passwordHash))return res.status(401).json({error:'Invalid email or password'});res.json({token:sign(user),user:{id:user.id,name:user.name,workspace:user.workspaceId.name}})});
router.get('/desks',requireAuth,async(req,res)=>res.json(await Desk.find({workspaceId:req.user.workspaceId,active:true}).sort({location:1,code:1})));
router.post('/desks',requireAuth,async(req,res)=>{const errors=validateDesk(req.body);if(errors.length)return res.status(422).json({error:'Invalid fields: '+errors.join(', ')});try{res.status(201).json(await Desk.create({...req.body,workspaceId:req.user.workspaceId,amenities:Array.isArray(req.body.amenities)?req.body.amenities:[]}))}catch(error){if(error.code===11000)return res.status(409).json({error:'Desk code already exists'});throw error}});
router.get('/bookings',requireAuth,async(req,res)=>{const query={workspaceId:req.user.workspaceId};if(req.query.date)query.date=req.query.date;res.json(await Booking.find(query).populate('deskId','code location floor').sort({date:1,createdAt:1}))});
router.post('/bookings',requireAuth,async(req,res)=>{const errors=validateBooking(req.body);if(errors.length)return res.status(422).json({error:'Invalid fields: '+errors.join(', ')});const desk=await Desk.findOne({_id:req.body.deskId,workspaceId:req.user.workspaceId,active:true});if(!desk)return res.status(404).json({error:'Desk not found'});try{const booking=await Booking.create({...req.body,workspaceId:req.user.workspaceId,employeeEmail:req.body.employeeEmail.toLowerCase()});res.status(201).json(await booking.populate('deskId','code location floor'))}catch(error){if(error.code===11000)return res.status(409).json({error:'Desk is already booked for this date'});throw error}});
router.delete('/bookings/:id',requireAuth,async(req,res)=>{const result=await Booking.deleteOne({_id:req.params.id,workspaceId:req.user.workspaceId});if(!result.deletedCount)return res.status(404).json({error:'Booking not found'});res.status(204).end()});
router.patch('/desks/:id',requireAuth,async(req,res)=>{if(typeof req.body.active!=='boolean')return res.status(422).json({error:'active must be boolean'});const desk=await Desk.findOneAndUpdate({_id:req.params.id,workspaceId:req.user.workspaceId},{active:req.body.active},{new:true});if(!desk)return res.status(404).json({error:'Desk not found'});res.json(desk)});
