import{Router}from'express';import bcrypt from'bcryptjs';import{requireAuth,tokenFor}from'./auth.js';import{Attendee,Event,Tenant,User}from'./models.js';import{attendeeSchema,eventMetrics,eventSchema,loginSchema,registerSchema}from'./validation.js';
export const router=Router();
const validate=s=>(req,res,next)=>{const r=s.safeParse(req.body);if(!r.success)return res.status(422).json({error:'Validation failed',details:r.error.issues});req.validated=r.data;next()};
router.post('/auth/register',validate(registerSchema),async(req,res,next)=>{try{const{organization,email,password}=req.validated;if(await User.exists({email:email.toLowerCase()}))return res.status(409).json({error:'Email already registered'});const tenant=await Tenant.create({name:organization});try{const user=await User.create({tenantId:tenant._id,email:email.toLowerCase(),passwordHash:await bcrypt.hash(password,12)});res.status(201).json({accessToken:tokenFor(user)})}catch(e){await Tenant.deleteOne({_id:tenant._id});throw e}}catch(e){next(e)}});
router.post('/auth/login',validate(loginSchema),async(req,res,next)=>{try{const u=await User.findOne({email:req.validated.email.toLowerCase()});if(!u||!await bcrypt.compare(req.validated.password,u.passwordHash))return res.status(401).json({error:'Invalid email or password'});res.json({accessToken:tokenFor(u)})}catch(e){next(e)}});
router.use(requireAuth);
router.get('/events',async(req,res,next)=>{try{res.json(await Event.find({tenantId:req.auth.tenantId}).sort({startsAt:1}))}catch(e){next(e)}});
router.post('/events',validate(eventSchema),async(req,res,next)=>{try{res.status(201).json(await Event.create({...req.validated,tenantId:req.auth.tenantId}))}catch(e){next(e)}});
router.patch('/events/:id/status',async(req,res,next)=>{try{if(!['draft','open','closed'].includes(req.body.status))return res.status(422).json({error:'Invalid status'});const item=await Event.findOneAndUpdate({_id:req.params.id,tenantId:req.auth.tenantId},{status:req.body.status},{new:true});if(!item)return res.status(404).json({error:'Event not found'});res.json(item)}catch(e){next(e)}});
router.get('/events/:id/attendees',async(req,res,next)=>{try{if(!await Event.exists({_id:req.params.id,tenantId:req.auth.tenantId}))return res.status(404).json({error:'Event not found'});res.json(await Attendee.find({eventId:req.params.id,tenantId:req.auth.tenantId}).sort({name:1}))}catch(e){next(e)}});
router.post('/attendees',validate(attendeeSchema),async(req,res,next)=>{try{const event=await Event.findOne({_id:req.validated.eventId,tenantId:req.auth.tenantId});if(!event)return res.status(404).json({error:'Event not found'});if(event.status!=='open')return res.status(409).json({error:'Registration is not open'});const count=await Attendee.countDocuments({eventId:event._id,tenantId:req.auth.tenantId});if(count>=event.capacity)return res.status(409).json({error:'Event is at capacity'});res.status(201).json(await Attendee.create({...req.validated,email:req.validated.email.toLowerCase(),tenantId:req.auth.tenantId}))}catch(e){if(e?.code===11000)return res.status(409).json({error:'Email already registered for this event'});next(e)}});
router.patch('/attendees/:id/check-in',async(req,res,next)=>{try{const item=await Attendee.findOne({_id:req.params.id,tenantId:req.auth.tenantId});if(!item)return res.status(404).json({error:'Attendee not found'});if(item.checkedInAt)return res.status(409).json({error:'Attendee already checked in'});item.checkedInAt=new Date();await item.save();res.json(item)}catch(e){next(e)}});
router.get('/events/:id/dashboard',async(req,res,next)=>{try{const event=await Event.findOne({_id:req.params.id,tenantId:req.auth.tenantId}).lean();if(!event)return res.status(404).json({error:'Event not found'});const attendees=await Attendee.find({eventId:event._id,tenantId:req.auth.tenantId}).lean();res.json(eventMetrics(event,attendees))}catch(e){next(e)}});

