import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const base = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const cash = cents => new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(cents / 100);
async function api(path, options = {}) { const response = await fetch(base + path, { ...options, headers: { 'Content-Type': 'application/json', ...(localStorage.leaseToken ? { Authorization: `Bearer ${localStorage.leaseToken}` } : {}) } }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; }

function App() {
  const [token, setToken] = useState(localStorage.leaseToken || ''); const [mode, setMode] = useState('register'); const [properties, setProperties] = useState([]); const [leases, setLeases] = useState([]); const [metrics, setMetrics] = useState({}); const [error, setError] = useState('');
  const load = async () => { try { const [p, l, m] = await Promise.all([api('/properties'), api('/leases'), api('/dashboard')]); setProperties(p); setLeases(l); setMetrics(m); setError(''); } catch (e) { setError(e.message); } };
  useEffect(() => { if (token) load(); }, [token]);
  const submitAuth = async e => { e.preventDefault(); const f = new FormData(e.currentTarget); try { const payload = { email: f.get('email'), password: f.get('password'), ...(mode === 'register' ? { organization: f.get('organization') } : {}) }; const result = await api('/auth/' + mode, { method: 'POST', body: JSON.stringify(payload) }); localStorage.leaseToken = result.accessToken; setToken(result.accessToken); } catch (e) { setError(e.message); } };
  const addProperty = async e => { e.preventDefault(); const f = new FormData(e.currentTarget); try { await api('/properties', { method: 'POST', body: JSON.stringify({ name: f.get('name'), address: f.get('address'), units: Number(f.get('units')) }) }); e.currentTarget.reset(); load(); } catch (e) { setError(e.message); } };
  const addLease = async e => { e.preventDefault(); const f = new FormData(e.currentTarget); try { await api('/leases', { method: 'POST', body: JSON.stringify({ propertyId: f.get('propertyId'), unitLabel: f.get('unitLabel'), residentName: f.get('residentName'), residentEmail: f.get('residentEmail'), monthlyRentCents: Math.round(Number(f.get('rent')) * 100), depositCents: 0, startDate: f.get('startDate'), endDate: f.get('endDate'), status: 'active' }) }); e.currentTarget.reset(); load(); } catch (e) { setError(e.message); } };
  if (!token) return <main className="auth card"><h1>LeaseNest</h1><p>Know every unit, resident and renewal.</p><form onSubmit={submitAuth}>{mode === 'register' && <input name="organization" placeholder="Organization" required />}<input name="email" type="email" placeholder="Email" required /><input name="password" type="password" minLength="8" placeholder="Password" required /><button>{mode === 'register' ? 'Create account' : 'Sign in'}</button></form><button className="link" onClick={() => setMode(mode === 'register' ? 'login' : 'register')}>{mode === 'register' ? 'Already have an account?' : 'Create an account'}</button>{error && <p className="error">{error}</p>}</main>;
  return <><header><strong>LeaseNest</strong><button onClick={() => { delete localStorage.leaseToken; setToken(''); }}>Log out</button></header><main><section className="metrics">{[['Properties', metrics.properties], ['Occupancy', `${metrics.occupancyPercent || 0}%`], ['Monthly rent', cash(metrics.monthlyRentCents || 0)], ['Expiring soon', metrics.expiringSoon]].map(x => <div className="card" key={x[0]}><span>{x[0]}</span><b>{x[1] ?? 0}</b></div>)}</section>{error && <p className="error">{error}</p>}<section className="columns"><form className="card" onSubmit={addProperty}><h2>Add property</h2><input name="name" placeholder="Property name" required /><input name="address" placeholder="Address" required /><input name="units" type="number" min="1" placeholder="Units" required /><button>Add property</button></form><form className="card" onSubmit={addLease}><h2>Add active lease</h2><select name="propertyId" required><option value="">Select property</option>{properties.map(p => <option value={p._id} key={p._id}>{p.name}</option>)}</select><input name="unitLabel" placeholder="Unit" required /><input name="residentName" placeholder="Resident" required /><input name="residentEmail" type="email" placeholder="Resident email" required /><input name="rent" type="number" min="1" step=".01" placeholder="Monthly rent" required /><input name="startDate" type="date" required /><input name="endDate" type="date" required /><button>Add lease</button></form></section><section><h2>Lease register</h2><div className="leases">{leases.map(l => <article className="card" key={l._id}><div><b>{l.residentName}</b><span>{l.propertyId?.name} · Unit {l.unitLabel}</span></div><div><b>{cash(l.monthlyRentCents)}</b><span>{l.status} · ends {new Date(l.endDate).toLocaleDateString()}</span></div></article>)}</div></section></main></>;
}
createRoot(document.getElementById('root')).render(<App />);

