import{Router}from'express';import bcrypt from'bcryptjs';import mongoose from'mongoose';import{Claim,User,Warranty}from'./models.js';import{requireAuth,signToken}from'./auth.js';import{claimSchema,claimUpdateSchema,coverage,loginSchema,registerSchema,warrantySchema}from'./validation.js';
export const router=Router();
router.post('/auth/register',async(req,res,next)=>{try{const d=registerSchema.parse(req.body);if(await User.exists({email:d.email.toLowerCase()}))return res.status(409).json({error:'Email already registered'});const u=await User.create({tenantId:new mongoose.Types.ObjectId(),name:d.name,email:d.email,passwordHash:await bcrypt.hash(d.password,12)});res.status(201).json({token:signToken(u),workspace:d.workspace})}catch(e){next(e)}});
router.post('/auth/login',async(req,res,next)=>{try{const d=loginSchema.parse(req.body),u=await User.findOne({email:d.email.toLowerCase()});if(!u||!await bcrypt.compare(d.password,u.passwordHash))return res.status(401).json({error:'Invalid credentials'});res.json({token:signToken(u)})}catch(e){next(e)}});
router.use(requireAuth);
router.get('/warranties',async(req,res)=>{const warranties=await Warranty.find({tenantId:req.auth.tenantId}).sort({expiresOn:1}).lean();const result=await Promise.all(warranties.map(async w=>({...w,covered:coverage(w),claims:await Claim.find({tenantId:req.auth.tenantId,warrantyId:w._id}).sort({createdAt:-1}).lean()})));res.json(result)});
router.post('/warranties',async(req,res,next)=>{try{const d=warrantySchema.parse(req.body);res.status(201).json(await Warranty.create({...d,tenantId:req.auth.tenantId}))}catch(e){next(e)}});
router.post('/warranties/:id/claims',async(req,res,next)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(404).json({error:'Warranty not found'});const w=await Warranty.findOne({_id:req.params.id,tenantId:req.auth.tenantId});if(!w)return res.status(404).json({error:'Warranty not found'});if(!coverage(w))return res.status(409).json({error:'Warranty coverage is not active'});const d=claimSchema.parse(req.body);res.status(201).json(await Claim.create({...d,tenantId:req.auth.tenantId,warrantyId:w._id}))}catch(e){next(e)}});
router.patch('/claims/:id',async(req,res,next)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(404).json({error:'Claim not found'});const d=claimUpdateSchema.parse(req.body),claim=await Claim.findOneAndUpdate({_id:req.params.id,tenantId:req.auth.tenantId},d,{new:true});if(!claim)return res.status(404).json({error:'Claim not found'});res.json(claim)}catch(e){next(e)}});

