import{Router}from'express';import bcrypt from'bcryptjs';import mongoose from'mongoose';import{Client,Task,User}from'./models.js';import{requireAuth,signToken}from'./auth.js';import{clientSchema,loginSchema,progress,registerSchema,statusSchema,taskSchema}from'./validation.js';
export const router=Router();
router.post('/auth/register',async(req,res,next)=>{try{const d=registerSchema.parse(req.body);if(await User.exists({email:d.email.toLowerCase()}))return res.status(409).json({error:'Email already registered'});const u=await User.create({tenantId:new mongoose.Types.ObjectId(),name:d.name,email:d.email,passwordHash:await bcrypt.hash(d.password,12)});res.status(201).json({token:signToken(u),workspace:d.workspace})}catch(e){next(e)}});
router.post('/auth/login',async(req,res,next)=>{try{const d=loginSchema.parse(req.body),u=await User.findOne({email:d.email.toLowerCase()});if(!u||!await bcrypt.compare(d.password,u.passwordHash))return res.status(401).json({error:'Invalid credentials'});res.json({token:signToken(u)})}catch(e){next(e)}});
router.use(requireAuth);
router.get('/clients',async(req,res)=>{const clients=await Client.find({tenantId:req.auth.tenantId}).sort({targetDate:1}).lean();const result=await Promise.all(clients.map(async client=>{const tasks=await Task.find({tenantId:req.auth.tenantId,clientId:client._id}).sort({dueDate:1}).lean();return{...client,tasks,progress:progress(tasks)}}));res.json(result)});
router.post('/clients',async(req,res,next)=>{try{const d=clientSchema.parse(req.body);res.status(201).json(await Client.create({...d,tenantId:req.auth.tenantId}))}catch(e){next(e)}});
router.post('/clients/:id/tasks',async(req,res,next)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(404).json({error:'Client not found'});const client=await Client.findOne({_id:req.params.id,tenantId:req.auth.tenantId});if(!client)return res.status(404).json({error:'Client not found'});const d=taskSchema.parse(req.body);res.status(201).json(await Task.create({...d,tenantId:req.auth.tenantId,clientId:client._id}))}catch(e){next(e)}});
router.patch('/tasks/:id',async(req,res,next)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(404).json({error:'Task not found'});const d=statusSchema.parse(req.body);const task=await Task.findOneAndUpdate({_id:req.params.id,tenantId:req.auth.tenantId},d,{new:true});if(!task)return res.status(404).json({error:'Task not found'});res.json(task)}catch(e){next(e)}});
router.delete('/clients/:id',async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return res.status(404).json({error:'Client not found'});const client=await Client.findOneAndDelete({_id:req.params.id,tenantId:req.auth.tenantId});if(!client)return res.status(404).json({error:'Client not found'});await Task.deleteMany({tenantId:req.auth.tenantId,clientId:client._id});res.status(204).end()});

