import {Router} from 'express';import bcrypt from 'bcryptjs';import {Workspace,User,Asset,Event} from './models.js';import {requireAuth,sign} from './auth.js';import {validEmail,validateAsset,validateCheckout} from './validation.js';export const router=Router();
router.post('/auth/register',async(req,res,next)=>{const{workspace,name,email,password}=req.body;if(!workspace?.trim()||!name?.trim()||!validEmail(email)||String(password||'').length<8)return res.status(422).json({error:'Workspace, name, valid email, and password of 8+ characters are required'});try{if(await User.exists({email:email.toLowerCase()}))return res.status(409).json({error:'Email already registered'});const tenant=await Workspace.create({name:workspace});try{const user=await User.create({workspaceId:tenant.id,name,email,passwordHash:await bcrypt.hash(password,12)});res.status(201).json({token:sign(user),user:{id:user.id,name:user.name,workspace:tenant.name}})}catch(error){await Workspace.deleteOne({_id:tenant.id});throw error}}catch(error){if(error.code===11000)return res.status(409).json({error:'Email already registered'});next(error)}});
router.post('/auth/login',async(req,res)=>{const user=await User.findOne({email:String(req.body.email||'').toLowerCase()}).populate('workspaceId');if(!user||!await bcrypt.compare(req.body.password||'',user.passwordHash))return res.status(401).json({error:'Invalid email or password'});res.json({token:sign(user),user:{id:user.id,name:user.name,workspace:user.workspaceId.name}})});
router.get('/assets',requireAuth,async(req,res)=>{const query={workspaceId:req.user.workspaceId};if(req.query.status)query.status=req.query.status;res.json(await Asset.find(query).sort({createdAt:-1}))});
router.post('/assets',requireAuth,async(req,res)=>{const errors=validateAsset(req.body);if(errors.length)return res.status(422).json({error:'Invalid fields: '+errors.join(', ')});try{const asset=await Asset.create({...req.body,workspaceId:req.user.workspaceId});await Event.create({workspaceId:req.user.workspaceId,assetId:asset.id,action:'created',actor:req.user.email});res.status(201).json(asset)}catch(error){if(error.code===11000)return res.status(409).json({error:'Asset tag already exists'});throw error}});
router.post('/assets/:id/checkout',requireAuth,async(req,res)=>{const errors=validateCheckout(req.body);if(errors.length)return res.status(422).json({error:'Invalid fields: '+errors.join(', ')});const asset=await Asset.findOne({_id:req.params.id,workspaceId:req.user.workspaceId,status:'available'});if(!asset)return res.status(409).json({error:'Available asset not found'});asset.status='checked_out';asset.assignedTo=req.body.assignedTo;asset.dueDate=req.body.dueDate;await asset.save();await Event.create({workspaceId:req.user.workspaceId,assetId:asset.id,action:'checked_out',actor:req.user.email,details:'Assigned to '+asset.assignedTo});res.json(asset)});
router.post('/assets/:id/return',requireAuth,async(req,res)=>{const asset=await Asset.findOne({_id:req.params.id,workspaceId:req.user.workspaceId,status:'checked_out'});if(!asset)return res.status(409).json({error:'Checked-out asset not found'});asset.status='available';asset.assignedTo='';asset.dueDate='';await asset.save();await Event.create({workspaceId:req.user.workspaceId,assetId:asset.id,action:'returned',actor:req.user.email});res.json(asset)});
router.patch('/assets/:id/status',requireAuth,async(req,res)=>{if(!['available','maintenance','retired'].includes(req.body.status))return res.status(422).json({error:'Status must be available, maintenance, or retired'});const asset=await Asset.findOneAndUpdate({_id:req.params.id,workspaceId:req.user.workspaceId},{status:req.body.status,assignedTo:'',dueDate:''},{new:true});if(!asset)return res.status(404).json({error:'Asset not found'});const action=req.body.status==='available'?'returned':req.body.status;await Event.create({workspaceId:req.user.workspaceId,assetId:asset.id,action,actor:req.user.email});res.json(asset)});
router.get('/assets/:id/events',requireAuth,async(req,res)=>{const asset=await Asset.findOne({_id:req.params.id,workspaceId:req.user.workspaceId});if(!asset)return res.status(404).json({error:'Asset not found'});res.json(await Event.find({assetId:asset.id,workspaceId:req.user.workspaceId}).sort({createdAt:-1}))});
