import {Router} from 'express';import bcrypt from 'bcryptjs';import {Workspace,User,Cohort,Enrollment} from './models.js';import {requireAuth,sign} from './auth.js';import {validEmail,validateCohort,validateEnrollment} from './validation.js';export const router=Router();
router.post('/auth/register',async(req,res,next)=>{const{workspace,name,email,password}=req.body;if(!workspace?.trim()||!name?.trim()||!validEmail(email)||String(password||'').length<8)return res.status(422).json({error:'Workspace, name, valid email, and password of 8+ characters are required'});try{if(await User.exists({email:email.toLowerCase()}))return res.status(409).json({error:'Email already registered'});const tenant=await Workspace.create({name:workspace});try{const user=await User.create({workspaceId:tenant.id,name,email,passwordHash:await bcrypt.hash(password,12)});res.status(201).json({token:sign(user),user:{id:user.id,name:user.name,workspace:tenant.name}})}catch(error){await Workspace.deleteOne({_id:tenant.id});throw error}}catch(error){if(error.code===11000)return res.status(409).json({error:'Email already registered'});next(error)}});
router.post('/auth/login',async(req,res)=>{const user=await User.findOne({email:String(req.body.email||'').toLowerCase()}).populate('workspaceId');if(!user||!await bcrypt.compare(req.body.password||'',user.passwordHash))return res.status(401).json({error:'Invalid email or password'});res.json({token:sign(user),user:{id:user.id,name:user.name,workspace:user.workspaceId.name}})});
router.get('/cohorts',requireAuth,async(req,res)=>{const cohorts=await Cohort.find({workspaceId:req.user.workspaceId}).sort({startDate:1}).lean();const counts=await Enrollment.aggregate([{$match:{workspaceId:req.user.workspaceId,status:'enrolled'}},{$group:{_id:'$cohortId',count:{$sum:1}}}]);const map=new Map(counts.map(x=>[x._id.toString(),x.count]));res.json(cohorts.map(x=>({...x,enrolled:map.get(x._id.toString())||0})))});
router.post('/cohorts',requireAuth,async(req,res)=>{const errors=validateCohort(req.body);if(errors.length)return res.status(422).json({error:'Invalid fields: '+errors.join(', ')});res.status(201).json(await Cohort.create({...req.body,capacity:Number(req.body.capacity),workspaceId:req.user.workspaceId}))});
router.patch('/cohorts/:id/status',requireAuth,async(req,res)=>{if(!['draft','open','active','completed'].includes(req.body.status))return res.status(422).json({error:'Invalid cohort status'});const cohort=await Cohort.findOneAndUpdate({_id:req.params.id,workspaceId:req.user.workspaceId},{status:req.body.status},{new:true});if(!cohort)return res.status(404).json({error:'Cohort not found'});res.json(cohort)});
router.get('/enrollments',requireAuth,async(req,res)=>{const query={workspaceId:req.user.workspaceId};if(req.query.cohortId)query.cohortId=req.query.cohortId;res.json(await Enrollment.find(query).populate('cohortId','name topic').sort({createdAt:-1}))});
router.post('/enrollments',requireAuth,async(req,res)=>{const errors=validateEnrollment(req.body);if(errors.length)return res.status(422).json({error:'Invalid fields: '+errors.join(', ')});const cohort=await Cohort.findOne({_id:req.body.cohortId,workspaceId:req.user.workspaceId,status:{$in:['open','active']}});if(!cohort)return res.status(404).json({error:'Open cohort not found'});const enrolled=await Enrollment.countDocuments({cohortId:cohort.id,workspaceId:req.user.workspaceId,status:'enrolled'});if(enrolled>=cohort.capacity)return res.status(409).json({error:'Cohort is full'});try{res.status(201).json(await Enrollment.create({...req.body,workspaceId:req.user.workspaceId,learnerEmail:req.body.learnerEmail.toLowerCase()}))}catch(error){if(error.code===11000)return res.status(409).json({error:'Learner already enrolled'});throw error}});
router.patch('/enrollments/:id/progress',requireAuth,async(req,res)=>{const progress=Number(req.body.progress);if(!Number.isFinite(progress)||progress<0||progress>100)return res.status(422).json({error:'Progress must be from 0 to 100'});const enrollment=await Enrollment.findOneAndUpdate({_id:req.params.id,workspaceId:req.user.workspaceId},{progress,status:progress===100?'completed':'enrolled'},{new:true});if(!enrollment)return res.status(404).json({error:'Enrollment not found'});res.json(enrollment)});
