import{Router}from'express';import bcrypt from'bcryptjs';import{requireAuth,tokenFor}from'./auth.js';import{PurchaseRequest,Tenant,User}from'./models.js';import{loginSchema,metrics,registerSchema,requestSchema,reviewSchema}from'./validation.js';export const router=Router();const validate=s=>(q,r,n)=>{const x=s.safeParse(q.body);if(!x.success)return r.status(422).json({error:'Validation failed',details:x.error.issues});q.validated=x.data;n()};
router.post('/auth/register',validate(registerSchema),async(q,r,n)=>{try{const{organization,email,password}=q.validated;if(await User.exists({email:email.toLowerCase()}))return r.status(409).json({error:'Email already registered'});const t=await Tenant.create({name:organization});try{const u=await User.create({tenantId:t._id,email:email.toLowerCase(),passwordHash:await bcrypt.hash(password,12)});r.status(201).json({accessToken:tokenFor(u)})}catch(e){await Tenant.deleteOne({_id:t._id});throw e}}catch(e){n(e)}});
router.post('/auth/login',validate(loginSchema),async(q,r,n)=>{try{const u=await User.findOne({email:q.validated.email.toLowerCase()});if(!u||!await bcrypt.compare(q.validated.password,u.passwordHash))return r.status(401).json({error:'Invalid email or password'});r.json({accessToken:tokenFor(u)})}catch(e){n(e)}});router.use(requireAuth);
router.get('/requests',async(q,r,n)=>{try{r.json(await PurchaseRequest.find({tenantId:q.auth.tenantId}).sort({createdAt:-1}))}catch(e){n(e)}});
router.post('/requests',validate(requestSchema),async(q,r,n)=>{try{r.status(201).json(await PurchaseRequest.create({...q.validated,tenantId:q.auth.tenantId,status:'draft'}))}catch(e){n(e)}});
router.post('/requests/:id/submit',async(q,r,n)=>{try{const x=await PurchaseRequest.findOne({_id:q.params.id,tenantId:q.auth.tenantId});if(!x)return r.status(404).json({error:'Request not found'});if(x.status!=='draft')return r.status(409).json({error:'Only draft requests can be submitted'});x.status='submitted';await x.save();r.json(x)}catch(e){n(e)}});
router.post('/requests/:id/review',validate(reviewSchema),async(q,r,n)=>{try{const x=await PurchaseRequest.findOne({_id:q.params.id,tenantId:q.auth.tenantId});if(!x)return r.status(404).json({error:'Request not found'});if(x.status!=='submitted')return r.status(409).json({error:'Only submitted requests can be reviewed'});x.status=q.validated.decision;x.reviewerNote=q.validated.reviewerNote;x.reviewedAt=new Date();await x.save();r.json(x)}catch(e){n(e)}});
router.delete('/requests/:id',async(q,r,n)=>{try{const x=await PurchaseRequest.findOne({_id:q.params.id,tenantId:q.auth.tenantId});if(!x)return r.status(404).json({error:'Request not found'});if(x.status!=='draft')return r.status(409).json({error:'Only drafts can be deleted'});await x.deleteOne();r.status(204).end()}catch(e){n(e)}});
router.get('/dashboard',async(q,r,n)=>{try{r.json(metrics(await PurchaseRequest.find({tenantId:q.auth.tenantId}).lean()))}catch(e){n(e)}});

