import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
function App(){
 const[token,setToken]=useState(localStorage.releaseproof||'');const[releases,setReleases]=useState([]);const[mode,setMode]=useState('register');const[error,setError]=useState('');
 async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
 const load=()=>token&&api('/releases').then(setReleases).catch(e=>setError(e.message));useEffect(load,[token]);
 async function auth(e){e.preventDefault();try{const d=await api('/auth/'+mode,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});localStorage.releaseproof=d.token;setToken(d.token)}catch(x){setError(x.message)}}
 async function add(e){e.preventDefault();try{await api('/releases',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});e.currentTarget.reset();load()}catch(x){setError(x.message)}}
 async function pass(check){try{await api('/checks/'+check._id,{method:'PATCH',body:JSON.stringify({result:'passed',evidence:'Verified in dashboard'})});load()}catch(x){setError(x.message)}}
 if(!token)return <main className="auth"><section><h1>ReleaseProof</h1><p>Ship with evidence, not crossed fingers.</p></section><form onSubmit={auth}><h2>{mode==='register'?'Create QA workspace':'Sign in'}</h2>{mode==='register'&&<><input name="workspace" placeholder="Workspace" required/><input name="name" placeholder="Your name" required/></>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" minLength="8" placeholder="Password" required/><button>{mode==='register'?'Start testing':'Sign in'}</button><a onClick={()=>setMode(mode==='register'?'login':'register')}>{mode==='register'?'Use an existing account':'Create a workspace'}</a><p className="error">{error}</p></form></main>;
 return <><header><div><h1>ReleaseProof</h1><span>Release readiness workspace</span></div><button className="quiet" onClick={()=>{localStorage.removeItem('releaseproof');setToken('')}}>Sign out</button></header><main><div className="layout"><form onSubmit={add}><h2>Plan a release</h2><input name="name" placeholder="Release name" required/><input name="version" placeholder="Version" required/><input name="owner" placeholder="Owner" required/><label>Target date</label><input name="targetDate" type="date" required/><button>Create release</button></form><section><h2>Release board</h2><div className="cards">{releases.map(r=><article key={r._id}><div><span className="pill">{r.status}</span><b>{r.readiness.score}% ready</b></div><h3>{r.name} <small>{r.version}</small></h3><p>{r.owner} · {new Date(r.targetDate).toLocaleDateString()}</p><div>{r.checks.map(c=><div className="check" key={c._id}><span>{c.title}<small>{c.area} / {c.priority}</small></span><button disabled={c.result==='passed'} onClick={()=>pass(c)}>{c.result==='passed'?'Passed':'Mark passed'}</button></div>)}</div></article>)}</div></section></div><p className="error">{error}</p></main></>;
}createRoot(document.getElementById('root')).render(<App/>);

