import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{api}from'./api';import'./style.css';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);
function App(){const[token,setToken]=useState(localStorage.getItem('invoicepilot_token'));const[clients,setClients]=useState([]),[invoices,setInvoices]=useState([]),[error,setError]=useState(''),[mode,setMode]=useState('login');
async function load(){try{setClients(await api('/clients'));setInvoices(await api('/invoices'))}catch(e){setError(e.message)}}useEffect(()=>{if(token)load()},[token]);
async function auth(e){e.preventDefault();setError('');const body=Object.fromEntries(new FormData(e.currentTarget));try{const out=await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify(body)});localStorage.setItem('invoicepilot_token',out.token);setToken(out.token)}catch(e){setError(e.message)}}
async function addClient(e){e.preventDefault();try{await api('/clients',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});e.currentTarget.reset();load()}catch(e){setError(e.message)}}
async function addInvoice(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{await api('/invoices',{method:'POST',body:JSON.stringify({clientId:d.clientId,number:d.number,dueDate:d.dueDate,items:[{description:d.description,quantity:Number(d.quantity),rate:Number(d.rate)}]})});e.currentTarget.reset();load()}catch(e){setError(e.message)}}
function logout(){localStorage.removeItem('invoicepilot_token');setToken(null)}
if(!token)return <main className="auth"><span className="brand">INVOICEPILOT</span><h1>Invoices without the turbulence.</h1><section><div className="tabs"><button onClick={()=>setMode('login')} className={mode==='login'?'active':''}>Sign in</button><button onClick={()=>setMode('register')} className={mode==='register'?'active':''}>Register</button></div><form onSubmit={auth}>{mode==='register'&&<><input name="workspace" placeholder="Workspace" required/><input name="name" placeholder="Your name" required/></>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" minLength="8" placeholder="Password" required/><button>Continue</button></form>{error&&<p className="error">{error}</p>}</section></main>;
const outstanding=invoices.filter(i=>i.status!=='paid').reduce((s,i)=>s+i.total,0);return <main><header><div><span className="brand">INVOICEPILOT</span><h1>Revenue cockpit</h1></div><button className="ghost" onClick={logout}>Log out</button></header>{error&&<p className="error">{error}</p>}<div className="stats"><article><span>Outstanding</span><strong>{money(outstanding)}</strong></article><article><span>Invoices</span><strong>{invoices.length}</strong></article><article><span>Clients</span><strong>{clients.length}</strong></article></div><div className="columns"><section><h2>Add client</h2><form onSubmit={addClient}><input name="name" placeholder="Client name" required/><input name="email" type="email" placeholder="Billing email" required/><input name="company" placeholder="Company"/><button>Save client</button></form><ul>{clients.map(c=><li key={c._id}><b>{c.name}</b><small>{c.company||c.email}</small></li>)}</ul></section><section><h2>Create invoice</h2><form onSubmit={addInvoice}><select name="clientId" required defaultValue=""><option value="" disabled>Select client</option>{clients.map(c=><option value={c._id} key={c._id}>{c.name}</option>)}</select><input name="number" placeholder="INV-001" required/><input name="dueDate" type="date" required/><input name="description" placeholder="Line item" required/><div className="row"><input name="quantity" type="number" min=".01" step=".01" placeholder="Qty" required/><input name="rate" type="number" min="0" step=".01" placeholder="Rate" required/></div><button>Create invoice</button></form></section></div><section><h2>Recent invoices</h2><div className="table">{invoices.map(i=><article key={i._id}><div><b>{i.number}</b><small>{i.clientId?.name}</small></div><strong>{money(i.total)}</strong><span className={`status ${i.status}`}>{i.status}</span></article>)}{!invoices.length&&<p>No invoices yet.</p>}</div></section></main>}
createRoot(document.getElementById('root')).render(<App/>);

